ACTION_OK = 'Ok'
ACTION_ALARM = 'Alarm'
ACTION_INSUFFICIENT_DATA = 'InsufficientData'
ACTIONS_NONE = ()
ACTIONS_OK_ALARM = (ACTION_OK, ACTION_ALARM)
ACTIONS_ALL = (ACTION_OK, ACTION_ALARM, ACTION_INSUFFICIENT_DATA)
