FROM alpine:3.4

ARG PYTHON_VERSION=3

COPY requirements.txt /app/requirements.txt
COPY src/test/requirements.txt /app/test-requirements.txt
COPY install.sh /app/install.sh

RUN /app/install.sh

COPY src/ /app
WORKDIR /app

VOLUME '/build'

ENTRYPOINT [ "nosetests", \
	"--with-xunit", "--xunit-file=/build/nosetests.xml", \
	"--with-coverage", "--cover-package=spacel", "--cover-xml", "--cover-xml-file=/build/coverage.xml", \
        "test/"]
